### ISSUE TITLE
Taxon seed

### ISSUE THREAD

**Issue by betovicentini** [opendatabio/opendatabio#118]
Seed for the taxon table remove unnamed nodes from the APG IV phylogeny

**Comment by betovicentini** [comment]
Clades named XXX_to_XXX from the tree by [Gastauer 2017](http://www.scielo.br/pdf/abb/v31n2/0102-3306-abb-31-02-00191.pdf) and other  unnamed nodes from this tree were removed from the taxon seed table attached. Still missing the MobotID and [Reflora](http://floradobrasil.jbrj.gov.br/) links to add to this.
This seed taxon table contains all relevant nodes from Gastauer 2017 big tree for families in Brazil Flora, and include all valid species and infra-specific taxa listed in this flora.

**Comment by andrechalom** [comment]
Note: Reflora integration is not set up. If this should be done before version 1.0, please open an appropriate issue so we can work out the time allocation for it.

**Comment by andrechalom** [comment]
This issue is a duplicate from #57.

**Comment by andrechalom** [comment]
I'm having to adapt some code to accept the character "×" in taxon names (note, that's a mutliplication sign, (U+00D7), not a lowercase x). It occurs in hybrid names, such as Mickelia ×atrans. This character is not being recognized in regex as alphanumeric, which causes all kind of trouble.

**Comment by andrechalom** [comment]
Taxon seed now live with all names except nothospecies and infraspecific.

- [ ] Include nothotaxa
- [ ] Include infraspecific in seed
- [ ] Include the installation commands to download and install seeds
