### ISSUE TITLE
Set default person for data entry

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#133]
- [x] as collector
- [x] as identifier
- [x] as tagging team
- [x] in measurement

**Comment by betovicentini** [comment]
I can prep a seeds for main botanical collectors and specialists

**Comment by andrechalom** [comment]
I think we're speaking of different things here. This issue was related to setting the default value of the "collector", "identified by", etc fields in the "Create Plant", "Create Measurement", etc screens. This is being implemented in commit d24f416. 

The list of botanical collectors is a different issue; also I don't know if this should be done as a database seed, or if this should be done individually in our installation of OpenDataBio.
