### ISSUE TITLE
Show taxon authors 

### ISSUE THREAD

**Issue by betovicentini** [opendatabio/opendatabio#142]
Taxon authors for species and infra-species categories are relevant to navigate and query:
Tab list names for quick search here [http://opendatabio.ib.usp.br/opendatabio/taxons](http://opendatabio.ib.usp.br/opendatabio/taxons)
should include authors, this allows _Ocotea sp.1 Vicentini_ to be diferentiated by _Ocotea sp.1 Chalom,_ for example.

**Comment by andrechalom** [comment]
Should this be done only for morphospecies or all species?

**Comment by betovicentini** [comment]
Good for memorization, so for all species!
