### ISSUE TITLE
Translate interface messages

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#149]

**Comment by allophilia** [comment]
## Dúvidas sobre tradução para o português (br) e pequenas questionamentos a respeito da nomenclatura no inglês:

1. Como traduzir **accepted name**? Valid name é outro termo válido para accepted name?
2. **Acronym** deve ser traduzido como acrônimo ou como sigla?
3. O que é o **IH site** mencionado na mensagem de erro relacionado a *acronym*?
4. **Collector** é uma referência a quem coletou algum dado ou um termo do software?
5. Como deve ser tratada a tradução de **termos do latim**?
	- Index Herbarium deve ser traduzido como Índice Herbarium?
	- Herbaria e Herbarium devem ser traduzidos?
	- Datum deve ser traduzido? Se sim, como Dado ou de outra forma?
	- etc
6. **Measurement** deve ser traduzido como medida ou como medição? 
7. Maiúsculas: várias entredas em inglês possuem uma palavra com a primeira letra maiúscula, como *Person*. 
	- Isso é relacionado às entradas do banco? 
	- Algumas vezes, porém, essas palavras se encontram no minúsculo. Devemos padronizá-las com a primeira letra maiúscula, corrigindo assim as entradas em inglês também?
8. Há uma *key* nomeada `persons`. Sua entrada no inglês é **Persons**. Existe uma razão para isso ou devemos alterá-la para **People**?
9. As *keys* `detail` e `details` ambas possuem como suas entradas no inglês **Details**. Devo alterar `detail` para **Detail** e resolver situações similares da mesma forma?
10. Qual deve ser a tradução para **job**? Processo? Trabalho? Tarefa?
11. Devemos manter **ID**, **tag** e **log** sem alterações no português ou devemos traduzir os termos?
12. Como devemos traduzir **range**? Alcance? Intervalo? Extensão?
13. Devemos traduzir **Dataset**? Se sim, devemos usar *Conjundo de Dados* ou *Set de Dados*?
14. A que se referem as siglas **IRN**, **IPNI** e **MOBOT**?
15. Como lidar com **Mycobank**?

**Comment by andrechalom** [comment]
> 1. Como traduzir **accepted name**? Valid name e validly published name são outros termos válidos 
para accepted name?

Há um certo nó em torno de "nome válido" vs "nome aceito", que tem tratamentos diferentes em botânica e zoologia. A princípio, "accepted name" e "nome aceito" deveriam ser os termos usados no OpenDataBio. 

> 2. **Acronym** deve ser traduzido como acrônimo ou como sigla?

Sigla.

> 3. O que é o **IH site** mencionado na mensagem de erro relacionado a *acronym*?

IH site é o Index Herbariorum, um site que compila informações de herbários. Como é o nome próprio do site, ele não deve ser traduzido: http://sweetgum.nybg.org/science/ih/

> 4. **Collector** é uma referência a quem coletou algum dado ou um termo do software?

Collector(s) é quem coletou um voucher. Tagging team é a(s) pessoa(s) responsáveis por marcar uma planta em campo. Measurer é a(s) pessoa(s) responsáveis por uma medição. Por outro lado, a pessoa responsável por identificar uma planta ou espécime está listada na interface como "Identified by"; será que devemos trocar tudo para "collected by", "tagged by" e "measured by"?

> 5. Como deve ser tratada a tradução de **termos do latim**?
>	- Index Herbarium deve ser traduzido como Índice Herbarium?
>	- Herbaria e Herbarium devem ser traduzidos?
>	- Datum deve ser traduzido? Se sim, como Dado ou de outra forma?
>	- etc

IH, ver 3 acima. De resto, o que não é nome próprio a princípio deve ser traduzido, tomando cuidado com os plurais: herbarium = herbário; herbaria = herbário. Exceção para isso é o datum, que aparentemente é usado em latim mesmo em textos em português: https://pt.wikipedia.org/wiki/Datum

> 6. **Measurement** deve ser traduzido como medida ou como medição? 

Medida. Acredito que medição é o processo de tirar uma medida, correto?

> 7. Maiúsculas: várias entradas em inglês possuem uma palavra com a primeira letra maiúscula, como *Person*. 
>	- Isso é relacionado às entradas do banco? 
>	- Algumas vezes, porém, essas palavras se encontram no minúsculo. Devemos padronizá-las com a primeira letra maiúscula, corrigindo assim as entradas em inglês também?

Sim, as entradas em maiúscula são os objetos do banco de dados (às quais correspondem as telas do sistema). Acredito que é bom padronizar tudo em maiúscula: Person, Dataset, Project, Plant, etc...

> 8. Há uma *key* nomeada `persons`. Sua entrada no inglês é **Persons**. Existe uma razão para isso ou devemos alterá-la para **People**?

People. Os objetos de banco de dados/php usam persons por conveniência.

> 9. As *keys* `detail` e `details` ambas possuem como suas entradas no inglês **Details**. Devo alterar `detail` para **Detail** e resolver situações similares da mesma forma?

Acredito que é melhor pesquisar isso caso a caso. No caso de "detail", acho que é apenas um typo, deveria ser "details" em todos os casos.

> 10. Qual deve ser a tradução para **job**? Processo? Trabalho? Tarefa?
> 11. Devemos manter **ID**, **tag** e **log** sem alterações no português ou devemos traduzir os termos?

A princípio, eu deixaria ID, tag, log e job em inglês. São palavras (ou siglas) de amplo uso.

> 12. Como devemos traduzir **range**? Alcance? Intervalo? Extensão?

Intervalo. 

> 13. Devemos traduzir **Dataset**? Se sim, devemos usar *Conjundo de Dados* ou *Set de Dados*?

Acho que o melhor é Conjunto de dados.

> 14. A que se referem as siglas **IRN**, **IPNI** e **MOBOT**?
> 15. Como lidar com **Mycobank**?

IRN é a chave de identificação de um herbário no IH; IPNI, MOBOT e Mycobank são nomes dos sites usados pela API de taxonomia. Todos ficam inalterados em português.

**Comment by allophilia** [comment]
Como devemos traduzir **Trait**? Variável? Característica?
@betovicentini

**Comment by betovicentini** [comment]
Trait - melhor traduzir como _Variável_  que é genérico
Plot - Parcela/SubParcela - pois serve para os dois.  

Alguns termos, tanto em inglês como em português, deveríamos seguir a terminologia do Darwin Core [http://rs.tdwg.org/dwc/](http://rs.tdwg.org/dwc/), pois já existe um padrão para isso.  

O SibBr traduziu para o português aqui [http://www.sibbr.gov.br/areas/index.php?area=publicar&subarea=termos-dwc][http://www.sibbr.gov.br/areas/index.php?area=publicar&subarea=termos-dwc]

Várias de suas dúvidas acima estão definidos no DWC, portanto, tanto a versão em inglês como em português poderia seguir essa ontologia.

**Comment by andrechalom** [comment]
Tentei acessar a interface do Darwin Core, mas estou tendo muita
dificuldade em entender o que é relevante para o ODB. Vc poderia listar os
termos que estamos usando e que deveriam ser modificados?

On Oct 30, 2017 08:30, "Alberto Vicentini" <notifications@github.com> wrote:

Trait - melhor traduzir como *Variável* que é genérico
Plot - Parcela/SubParcela - pois serve para os dois.

Alguns termos, tanto em inglês como em português, deveríamos seguir a
terminologia do Darwin Core http://rs.tdwg.org/dwc/, pois já existe um
padrão para isso.

O SibBr traduziu para o português aqui [http://www.sibbr.gov.br/
areas/index.php?area=publicar&subarea=termos-dwc][http://
www.sibbr.gov.br/areas/index.php?area=publicar&subarea=termos-dwc]

Várias de suas dúvidas acima estão definidos no DWC, portanto, tanto a
versão em inglês como em português poderia seguir essa ontologia.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/opendatabio/opendatabio/issues/149#issuecomment-340404328>,
or mute the thread

**Comment by allophilia** [comment]
Estou adiantando a tradução, mas outras dúvidas surgiram.

18.  Como deve ser feita a tradução da nomenclatura de relações parentais?
     - **Parent** (Ex: "Unable to autodetect parent!")
       - Obs: Há usos de **parent** e afins tanto em relação a taxonomia quanto hierarquia das localizações
     - **Senior** (Ex: "The senior indicated is from a taxonomic level...")
     - **Junior** (Ex: "APIs indicate that this name is a junior synonym...")
19. Como lidar com termos relativos à geometria?
    - Ex: "Store here the geometry of the location. This field accepts a **Well Known Text** of a Point, **LineString**, Polygon or MultiPolygon..."
20. A que se refere **node** em "*Impossible to move **node** to this parent.*"?
21. A *key* `plant_modifier_hint` deve ter os termos em latim adaptados ao português? Ex: "**sensu lato**" -> "lato sensu"
22. Lembrete: Verificar possível ambiguidade nos valores da *key* `plant_identification_date_hint`. Inserir "a data/the date" para remover ambiguidade?
23. Lembrete: Verificar uso de "parcela" e possível necessidade de inserir "/sub-parcela" em seguida.
24. Lembrete: Verificar possível ambiguidade nos valores da *key* `project_privacy_hint`.
25. Observação: Devido a inconsistências nas entradas, os usos de **Taxons** e **Taxa** quando em inglês foram padronizados como Taxa. Em português manteve-se o uso de Táxons.
26. Observação: **Viewers** foram traduzidos como *Observadores*.
27. Observação: Revisar descrição dos tipos de variáveis.
28. Lembrete: Verificar tradução da *key* `userjobs_hint` e se os status são traduzidos ou não para então poder completá-la.

De qualquer forma, continuarei editando a tradução com o tempo, mas devo lançar uma versão preliminar logo menos. Alguns elementos podem ter sido traduzidos sem o conhecimento de seus contextos no sistema e assim podem ser alterados logo.

**Comment by andrechalom** [comment]
> 18.  Como deve ser feita a tradução da nomenclatura de relações parentais?
     - **Parent** (Ex: "Unable to autodetect parent!")
       - Obs: Há usos de **parent** e afins tanto em relação a taxonomia quanto hierarquia das localizações

Boa pergunta. Em todos os casos, eles representam o nível superior de hierarquia.

> - **Senior** (Ex: "The senior indicated is from a taxonomic level...")
> - **Junior** (Ex: "APIs indicate that this name is a junior synonym...")

Sênior e júnior são usados em português

> 19. Como lidar com termos relativos à geometria?
    - Ex: "Store here the geometry of the location. This field accepts a **Well Known Text** of a Point, **LineString**, Polygon or MultiPolygon..."

WKT é um padrão de representação de dados, fica em inglês mesmo. Os outros termos são usados para descrever os objetos WKT, podem ficar em inglês ou ser traduzidos como ponto, linha, polígono, multipolígono.

> 20. A que se refere **node** em "_Impossible to move **node** to this parent._"?

É melhor mudar o original para o nome do objeto. Essa mensagem pode aparecer para Locations e Taxons, não é? "Impossível mover esse táxon para ... "

> 21. A _key_ `plant_modifier_hint` deve ter os termos em latim adaptados ao português? Ex: "**sensu lato**" -> "lato sensu"

Lato sensu costuma ser usado em outros contextos, em nomenclatura taxonômica acredito que o mais usado é "sensu lato" mesmo em português.

**Comment by betovicentini** [comment]
Minhas sugestões:

1) Darwin core é complicado, mas em alguns casos teremos que ajustar isso para facilitar movimento entre bases de dados

> 18. - [x] Como deve ser feita a tradução da nomenclatura de relações parentais?
     - **Parent** (Ex: "Unable to autodetect parent!")
       - Obs: Há usos de **parent** e afins tanto em relação a taxonomia quanto hierarquia das localizações
     - **Senior** (Ex: "The senior indicated is from a taxonomic level...")
     - **Junior** (Ex: "APIs indicate that this name is a junior synonym...")

**Parent** - para taxon usar :  _Taxon Pai_  e _Localidade Pai_  e no help explicar o que significa em detalhe.
**Senior** - a palavra chave é sinônimo, portanto isso precisa ficar claro no help e nos termos. O campo poderia ser:  "É sinônimo de"   (pois isso aplica apenas a nomes inválidos). No flora do Brasil eles usam em inglês:  "Is synonym" 
**Junior** - no flora do Brasil eles usam:  "Has synonym". Poderia ser:  "Tem sinônimos" ou "São sinônimos" (ai fica direto).

> 19. - [x] Como lidar com termos relativos à geometria?
    - Ex: "Store here the geometry of the location. This field accepts a **Well Known Text** of a Point, **LineString**, Polygon or MultiPolygon..."
> 20. - [x] A que se refere **node** em "_Impossible to move **node** to this parent._"?
> 21. - [x] A _key_ `plant_modifier_hint` deve ter os termos em latim adaptados ao português? Ex: "**sensu lato**" -> "lato sensu"

De acordo com @andrechalom 

>22. - [x] _Lembrete_: Verificar possível ambiguidade nos valores da _key_ `plant_identification_date_hint`. Inserir "a data/the date" para remover ambiguidade?

Isso não é uma questão de padronizar na base o uso da data em Inglês?

> 23. - [ ] _Lembrete_: Verificar uso de "parcela" e possível necessidade de inserir "/sub-parcela" em seguida.

Subparcela deveria aparecer se Pai é Parcela ou Plot

> 24. - [x] _Lembrete_: Verificar possível ambiguidade nos valores da _key_ `project_privacy_hint`.
> 25. _Observação_: Devido a inconsistências nas entradas, os usos de **Taxons** e **Taxa** quando em inglês foram padronizados como Taxa. Em português manteve-se o uso de Táxons.

> 26. _Observação_: **Viewers** foram traduzidos como _Observadores_.

Não é melhor "Visualizadores" mesmo. Afinal, é quem pode visualizar os dados e não tem permissão de edição.

**Comment by allophilia** [comment]
> **Parent** - para taxon usar :  _Taxon Pai_  e _Localidade Pai_  e no help explicar o que significa em detalhe.
> **Senior** - a palavra chave é sinônimo, portanto isso precisa ficar claro no help e nos termos. O campo poderia ser:  "É sinônimo de"   (pois isso aplica apenas a nomes inválidos). No flora do Brasil eles usam em inglês:  "Is synonym" 
> **Junior** - no flora do Brasil eles usam:  "Has synonym". Poderia ser:  "Tem sinônimos" ou "São sinônimos" (ai fica direto).

**Parent:** Ok, por enquanto vou manter como está no PR #163 . Devo me aprofundar na parte interna do odb na próxima semana e verificar mais precisamente em que situações as mensagens são mostradas para verificar se são mensagens distintas para Táxons e para Localizações e então insiro as mudanças.

**Senior e Junior:** Vou manter os campos como _Sênior_ e _Júnior_ por enquanto, mas alterar as mensagens de help para explicar melhor. Futuramente irei verificar o uso dos campos para verificar que a mensagem seria usada apenas no caso desejado e então tentarei alterar a tradução deles. ^^


> >22. - [x] _Lembrete_: Verificar possível ambiguidade nos valores da _key_ `plant_identification_date_hint`. Inserir "a data/the date" para remover ambiguidade?
> 
> Isso não é uma questão de padronizar na base o uso da data em Inglês?
Sim! Já corrigi isso na última revisão. Está no PR #163 =D

> > 23. - [ ] _Lembrete_: Verificar uso de "parcela" e possível necessidade de inserir "/sub-parcela" em seguida.
> 
> Subparcela deveria aparecer se Pai é Parcela ou Plot

Então Subparcela seria um novo nível de localização, que precisaria ser introduzido no sistema. Vou procurar discussão referente ao modelo dos dados aqui assim que me inteirar mais da parte interna do odb.


> > 26. _Observação_: **Viewers** foram traduzidos como _Observadores_.
> 
> Não é melhor "Visualizadores" mesmo. Afinal, é quem pode visualizar os dados e não tem permissão de edição.

De fato é uma tradução melhor, vou corrigir já e atualizar o PR #163 em aberto. =)

**Comment by betovicentini** [comment]
Substituir Nome da Localização por "Nome da Localidade"  e qualquer Localização por Localidade nesse contexto

**Comment by allophilia** [comment]
> Substituir Nome da Localização por "Nome da Localidade" e qualquer Localização por Localidade nesse contexto

A escolha ao traduzir **Location** como _Localização_ se deu em razão da nomenclatura tipicamente utilizada em softwares (ex: location services -> serviços de localização).

Verificando mais a fundo, encontrei que _Localidade_ é o termo clássico utilizado em biologia para identificar o "lugar geográfico onde se encontra a origem do tipo de uma espécie", segundo _Houaiss_ e segundo uma página da Wikipédia sobre [tipo nomenclatural de um táxon](https://pt.wikipedia.org/wiki/Tipo_nomenclatural).

A escolha de _Localidade_ no lugar de _Localização_ ou mesmo _Local_ se deve a este contexto? Verificarei com cuidado as ocorrências em mensagens para corrigir as situações que se enquadram neste caso.

**Comment by allophilia** [comment]
Dado o último comentário, decidi deixar um registro neste comentário sobre a razão pela escolha de traduzir **Viewers** como _Visualizadores_ e não _Observadores_, caso ocorram discussões futuras.

Inicialmente a tradução escolhida foi _observadores_, por se tratar de uma palavra mais utilizada no português. Após o comentário de @betovicentini acima, considerei _visualizadores_ como uma opção.

Apesar de palavra menos frequente no português (inclusive ausente em muitos dicionários), o uso do verbo 'visualizar' como tradução de 'view' é comum em softwares para indicar que o usuário possui permissão para visualizar o arquivo (conforme imagens abaixo demonstram). As palavras derivadas, 'visualizador' e 'visualizadores' também são comumente utilizadas para se referir a programas que permitam visualizar arquivos de formatos específicos.

Considerando-se que o uso de _Viewers_ em mensagens do OpenDataBio serve como indicador de quais usuários podem visualizar dados e que o uso de _observador_ poderia eventualmente confundir um leitor, que poderia entender _observador_ como aquele que realiza uma observação experimental, optou-se então por _Visualizadores_ neste momento, dado que a palavra da qual é derivada já é associada ao significado desejado.

---
**Imagens:**
<img width="300" alt="screen shot 2017-11-06 at 21 49 46" src="https://user-images.githubusercontent.com/8948655/32471293-a6a357c8-c343-11e7-8030-f2af63017787.png"> <img width="300" alt="screen shot 2017-11-06 at 21 50 38" src="https://user-images.githubusercontent.com/8948655/32471294-a6c51174-c343-11e7-8d55-6c0f0ae4753e.png">
*_Imagens do serviço Google Drive_

**Comment by andrechalom** [comment]
Correto. Estou aguardando as seguintes correções e faço o merge. Do restante da tradução, acho "pai" uma tradução maisoumenos pra "parent" no nosso contexto. Talvez seja melhor algo como "precursor"?

- [ ] Localização > Localidade (pois a palavra é sempre usada nesse contexto no ODB)
- [ ] 'export_name' deveria ser 'Nome para exportação'
- [ ] Eu traduziria Full Users como usuários plenos. Isso serve também para os hints nos quais essa expressão aparece
- [ ] 'plant_identification_date_hint' em português não está fazendo sentido, acho que vc mudou de ideia no meio da frase?
 
Com isso, encerramos esse issue.
