### ISSUE TITLE
Support image uploads / visualization

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#158]
- [x] Should the images be stored inside the database or in the filesystem?
- [x] Implement image tags
- [x] Support thumbnails
- [x] Check http://image.intervention.io/
- [ ] NOTE: check the warnings about using binary files in Laravel Queues
- ~~Add some "timestamp" to images to benefit from cache when possible, but have a way to invalidate them~~
- [x] Migration / model
- [x] Policy?
- [ ] Views for showing images
- [x] Views for uploading images

**Comment by betovicentini** [comment]
> - [ ] Should the images be stored inside the database or in the filesystem?
Choose what make image handling faster and is easier to organize. Store in the filesystem seems easier.

**Comment by andrechalom** [comment]
Going for filesystem for performance considerations, as the images are expected to be quite large, see [here](https://www.microsoft.com/en-us/research/publication/to-blob-or-not-to-blob-large-object-storage-in-a-database-or-a-filesystem/?from=http%3A%2F%2Fresearch.microsoft.com%2Fpubs%2F64525%2Ftr-2006-45.pdf) for the technical view.

It is important to notice that, with filesystem images, the system administrators responsible for the Opendatabio installations should keep this in mind when planning backups.

**Comment by andrechalom** [comment]
For ease of maintenance, all images will be renamed following a standard procedure, and converted to jpg.

**Comment by andrechalom** [comment]
Renaming Image -> Picture due to several namespace clashes
