### ISSUE TITLE
Support "markable tables" and data filters

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#160]
How should this be implemented? What are the important features here?

**Comment by betovicentini** [comment]
Please clarify what you mean.

**Comment by andrechalom** [comment]
This was a feature you requested, back on our meetings in March. But I'm not entirely sure what should this accomplish. The idea is to have checkboxes on all of the datatables, but how should these checkboxes behave?

- [ ] If I click "export", the system should only export the marked items, right? 
- [ ] There should be a button for "clear selection"?
- [ ] If I navigate on the datatable (page 1, page 2, etc), the selection should remain unchanged?
- [ ] If I navigate away from this screen to other pages, the selection should remain unchanged?
- [ ] Is there any other feature that this checkboxes must have? Any other behavior?

**Comment by betovicentini** [comment]
I've added this to the Plant datatable to allow batch plant identification. Simple plugin that works well with server-side datatable. Easy to add to all needed export or process datatables, and could integrate this with the Export buttons, which need customizations for better exported tables.

**Comment by betovicentini** [comment]
Implemented for large table exports
