### ISSUE TITLE
API documentation and implantation

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#161]
- [x] Location API
- [x] Taxon API
- [x] Person API
- [x] Plant API
- [x] Herbarium samples API
- [ ] Measurements API
- [ ] References API

I don't think the other objects should be exposed by API - is there anything else that should be?

**Comment by betovicentini** [comment]
Are these opendatabio API or external API for this objects. 
Opendatabio API could have a Dataset API to download data directly in particular formats for analyses? Then a Measurement API may not be needed, because it will require the permissions regulated by Datasets and Projects.

**Comment by andrechalom** [comment]
These are for OpenDataBio APIs. I believe that what you are calling "Dataset API" is the same thing that I'm calling "Measurements API".

**Comment by betovicentini** [comment]
The API has been updated. Closing.
