### ISSUE TITLE
Data audit module

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#162]
- [ ] This should be documented
- [x] Check https://github.com/VentureCraft/revisionable

**Comment by andrechalom** [comment]
We may have issues with DB::raw fields, which are used extensively in ODB; see https://github.com/VentureCraft/revisionable/issues/293

**Comment by andrechalom** [comment]
Revisions should support
- [ ] DB:raw fields
- [ ] Pivot tables - see https://stackoverflow.com/questions/36920857/laravel-log-revisions-for-many-to-many-relationships
- [ ] Translatable field names

**Comment by andrechalom** [comment]
Notes for current implementation:

- Model boot methods must explicitly call `static::bootRevisionableTrait();`
- Related models can be mapped using `protected $relatedModels = ['revisionable_relation_id' => 'relationName'];

**Comment by andrechalom** [comment]
- [ ] Identification class may require some tweaking, as this is a class in which several "pivot" elements may be edited and should be recorded.

**Comment by andrechalom** [comment]
- [ ] Revisionable should be able to get the user from the running job. Somehow.

**Comment by andrechalom** [comment]
Data audit module aproved by skype 17/01, proceeding to implement. 

- [ ] Data history should have a more relevant description for identification changes (one line for each complete change, as opposed to one line for date, other for identifier)

**Comment by betovicentini** [comment]
I am starting to work on this, as it remains unimplemented. I've searched and think there is another package [](https://github.com/owen-it/laravel-auditing) for auditing that seems a better choice at the moment. I will try that focusing on identifications changes which is the last thing I need to move and start using the system. But seems simple to audit any changes to models and it is easy to retrieve changes.

**Comment by betovicentini** [comment]
This is replaced by ActivityLog package in bigtest branch.
