### ISSUE TITLE
Location interface improvements

### ISSUE THREAD

**Issue by betovicentini** [opendatabio/opendatabio#165]
I added some comments #40  and #42  and #41, which relate to the issues referred here.  See #149   for translations to portuguese that require checking.

If Administrative level is country then parent should not be included, nor AutoDetect, because there is no level above country (Alternatively, should add continent)  

Table of registered locations:

- [ ] Should at least display the following fields for: LocationID, Nome, ParentName, AdminLevel, Path and all of them searchable (currently search only finds string in Location name, but there should be option to search either the whole path or the parent). If I want to quickly see all locations from Brasil, I should be able to see that.
- [ ] Add link to each element in location path, facilitation navigation
- [ ] current CSV exports only fields displayed in table. This is too simple. The export from here should include the full information of the location table, including all relevant fields that may allow the use of this table elsewhere (ID, name, parent, path, coordinates, geometry, dim-x, dim-y, start-x, start-y, etc...)

**Comment by andrechalom** [comment]
> The export from here should include the full information of the location table, including all relevant fields that may allow the use of this table elsewhere (ID, name, parent, path, coordinates, geometry, dim-x, dim-y, start-x, start-y, etc...)

Agreed for the most part. Adding the full geometry to the export is too heavy, and should probably be accessed by API.

**Comment by betovicentini** [comment]
This issue has been accounted for in version 0.9.
