### ISSUE TITLE
Measurements from the same specimen housed at different herbaria

### ISSUE THREAD

**Issue by ricoperdiz** [opendatabio/opendatabio#174]
I believe this is important, and it may be related to #164.  If we have more than one specimen for a certain collection, and we have access to all of these collections, housed in different herbaria, I believe we should be able to store measurements from each one of these specimens separately.

For example, suppose we have the voucher Terra 1000, with 3 duplicates, one at INPA, others at RB and NY.  I took measurements from each specimen in all of these herbaria. Then I decide to record these data on opendatabio, I have the option of pointing which herbarium those measurements belong., like attaching that dataset to a unique duplicate, not to the specimen.

**Comment by andrechalom** [comment]
The current data model was developed by @betovicentini request, explicitly
to attach the measurements to each specimen, and not to a duplicate. I
believe he is the right person to explain why this decision was made.

Any change to this now would involve a very deep reworking of the basic
data model, and is unfortunately out of scope for this project.

**Comment by betovicentini** [comment]
So far we can only link info to specimens, regardless of where they are. Nonetheless one option would be to include the option to select the Herbarium (among those related to the specimen) when registering a Variation of a Trait relative to Specimens (Vouchers).  @andrechalom  is this difficult to add?

**Comment by andrechalom** [comment]
This would increase the complexity of the system in several ways.

This would require adding a column for herbarium_id in the Measurement table, which would be meaningless in all other contexts. It would also mean that the measurement could be linked to a herbarium which does not have a sample of the specimen, as there is no direct link between these entities.

**Comment by betovicentini** [comment]
Adding one column, even if used for Specimens only, should not be problem. The link problem is more complex, but could be controlled by Herbaria associated with specimen for which the measurement is being registered. Only the Herbaria linked to the specimen would appear in the select box of the Measurement input

**Comment by andrechalom** [comment]
Adding a column can have lots of potential impact to the system stability and performance. We can discuss this in today's meeting.

**Comment by betovicentini** [comment]
Ok. Thinking about this. Perhaps a solution would be to have either optional TAG or NOTE to each measurement (had note, right?), regardless of type of related object. This would allow to just type an herbarium code as a note to the measurement and any other 'obs' the user would want. Would this complicate?

**Comment by andrechalom** [comment]
@ricoperdiz, we're adding the "notes" field to the Measurement table on version 0.7.3 (soon to be released), so you will be able to specify the herbarium in which the measurement was taken. Please check if this is enough for your uses.

**Comment by andrechalom** [comment]
Closing the issue after 1 month inactive. Please let us know if this is really fixed.
