### ISSUE TITLE
Add variables on taxa pages

### ISSUE THREAD

**Issue by ricoperdiz** [opendatabio/opendatabio#181]
Hi @betovicentini  and @andrechalom,

You decide what to do with this issue, actually it is just a request.

I believe we should have the option to have some variables associated to taxa. For example, for each taxon, besides displaying taxon name, author, bib reference, level, and valid status, we should have text variables, as notes, for:

- Protologue
- Full list of synonyms (this could be displayed on "related taxa tab")
- taxon description (this could be stored in a text variable OR as a dynamic description)
-  Field characters (this would be a valid option to include characters seen exclusively on the field OR adding some data that is usually present on a species description, but otherwise it would be difficult to be present in a dynamic description (e.g., "petioles usually glabrous OR, sometimes, with little scattered stiff trichomes etc))
- List of specimens
- Distribution
- Phenology
- Pollination
- Dispersal
 - Predation
- Taxonomic notes
- Etymology
- List of common names
- Conservation
- Uses
- List of references (a bib file)

What do you think? 

This would be extremely useful for taxonomic treatments, such as mine, and other members of our lab at INPA.

**Comment by andrechalom** [comment]
Hi! 

Some of these variables are present on the page for a specific taxon (such as [synonyms](http://opendatabio.ib.usp.br/opendatabio/taxons/15737) listed here for _Abarema adenophora_), and most of them can be added as custom variables. Unfortunately, they can't be placed on the taxon list, as this would cause the system to be extremely slow, but they can be exported as a table using the API. 

Some more specific notes:

> - Protologue

- [ ] I think this can be added as a custom report, as a protologue consists on several related information, right? Custom reports are one of the things that are still under development...

> - taxon description (this could be stored in a text variable OR as a dynamic description)
> - Field characters (this would be a valid option to include characters seen exclusively on the field OR adding some data that is usually present on a species description, but otherwise it would be difficult to be present in a dynamic description (e.g., "petioles usually glabrous OR, sometimes, with little scattered stiff trichomes etc))
> -  Phenology
> - Taxonomic notes
> - Etymology
> -  List of common names
> -  Uses

I would add those as custom text variables.

> - List of specimens

- [ ] This should be in the taxon report, I must have forgotten to implement it. 

> -  Distribution
> -  Pollination
> -  Dispersal
> -  Predation
> -  Conservation

I would add those as categorical variables. Of course, what is categorical and what is free text depends on the intended use for the data. Also predation and pollination can be added as "link" type variables, to register the herbivore / pollinator as a registered taxon. (see Measurements tab on _Abarema adenophora_).

> - List of references (a bib file)

That's a bit harder. In our current data model, bib references can be associated with taxons, datasets and measurements. We would need to define what list of references should be generated for a taxon - the references of all datasets that include measurements over the taxon? Or the references of all datasets that include measurements on plants/samples identified to a taxon?

**Comment by andrechalom** [comment]
Also, you can create the variables in our test server, I think that will help you see what can be done at the moment in the system, and what is still needed ;-)

**Comment by ricoperdiz** [comment]
Ok, @andrechalom, thanks for your opinion, and idea, and suggestions.

I will try again some of these things on the test server again, this was just to record these ideas, because I believe they are important. And some of them @betovicentini have already offered before on duckewiki, but they were not that refined, so it was difficult to see them or use them, actually.

Thank you.

R.

**Comment by andrechalom** [comment]
Closing the issue, please open it again if there is something still missing.
