### ISSUE TITLE
Interface design: lat / long selector are breaking on wide screens

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#183]
![27329657_2031515320208456_1564419737_o](https://user-images.githubusercontent.com/1994997/35308615-9cd16760-008f-11e8-9ff3-452019cf3c1d.png)

**Comment by birutaibm** [comment]
I am not sure if this is the cause, but the only one error that I found is at line 91 of resources/views/locations/create.blade.php. Please, try replace _label for="lat1"_ to _label for="long1"_ and see if this solves the problem.

**Comment by andrechalom** [comment]
Thanks for the input! 

I don't think these are related, but you're right in that line 91 is a mistake. Fixing this on the next version.
