### ISSUE TITLE
Installation on OSX supervisor message

### ISSUE THREAD

**Issue by betovicentini** [opendatabio/opendatabio#184]
Found this message during an installation of OpenDataBio in a Mac. Supervisor was previously installed and running.

Even after creating the file manually in  /usr/local/etc/supervisor.d, which is included in the filed /usr/local/etc/supervisord.conf, recognized by supervisor, the installer shows the message. 
No sure, if this is a problem, as the installation works fine (so far), but seems that adding the file does not change the behavior of the installer.
```
PHP dependencies installed dependencies successfully!
Could not find supervisor worker file!
Do you wish to review the sample Supervisor worker file? yes/[no] y
You should store the following lines in a file called
                /etc/supervisor/conf.d/opendatabio-worker.conf (Debian/Ubuntu) or 
                /etc/supervisor.d/opendatabio-worker.ini (ArchLinux)
(You will need root access for that)

;--------------
[program:opendatabio-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /Users/beto/opendatabio/app/artisan queue:work --sleep=3 --tries=1 --timeout=0 --daemon
autostart=true
autorestart=true
user=beto
numprocs=8
redirect_stderr=true
stdout_logfile=/Users/beto/opendatabio/app/storage/logs/supervisor.log
;--------------

```

**Comment by andrechalom** [comment]
I am unable to provide support for OSX. If you can work out the problem,
please feel free to send the correction in a pull request.

On Wed, Jan 24, 2018 at 8:47 PM, Alberto Vicentini <notifications@github.com

**Comment by betovicentini** [comment]
This was solved!
