### ISSUE TITLE
Installation under Proxy

### ISSUE THREAD

**Issue by betovicentini** [opendatabio/opendatabio#188]
I found a problem installing Opendatabio in an Ubuntu Server behind INPA's proxy.  The system is configured to work behind  a proxy and, apt-get, wget, and git clone, for example, work correctly. However, when running: php install, the composer installation fails (line 338 of Installer.php), because file_get_contents is used without proxy configuration.  And this step precedes the proxy input. Hence, perhaps this could be fixed by asking for the proxy before or getting from the environment specification the settings.

**Comment by andrechalom** [comment]
I think the only installation step that requires internet access is the
composer installation, if this is done beforehand I believe the install
will succeed. Can you test it? Maybe we should just add this as a specific
instruction on the Readme, as I don't know how many users will experience
this problem

**Comment by betovicentini** [comment]
not a opendatabio problem
