### ISSUE TITLE
Error at supervisor instructions during instalation

### ISSUE THREAD

**Issue by birutaibm** [opendatabio/opendatabio#189]
The installer request the user to edit the file `/etc/supervisor/conf.d/opendatabio-worker.conf` to insert some contents in it, but the last line is wrong. Please, replace in this instruction the line: `stdout_logfile=/home/odbserver/opendatabio/app/storage/logs/supervisor.log` by `stdout_logfile=/home/odbserver/opendatabio/storage/logs/supervisor.log`

**Comment by andrechalom** [comment]
Nice catch! 

As a matter of fact, the command to start the queue was incorrect was well! @betovicentini please notice that this may be related to the problems you had starting supervisor on your local installs

The incorrect line is:

https://github.com/opendatabio/opendatabio/blob/f5108faef47bcb6a70683ef16dd6d7fb16bac98f/app/Installer.php#L487

Which would render something like `command=php /home/odbserver/opendatabio/app/artisan queue:work etc etc`, when in fact this should be `command=php /home/odbserver/opendatabio/artisan queue:work etc etc` without the /app/!
