### ISSUE TITLE
Duplication on Location insertion

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#190]
Cross-issue from https://github.com/opendatabio/opendatabio-r/issues/14

**Comment by andrechalom** [comment]
Context: the rule for uniqueness in Location table is the pair `[parent, name]` - this allows for different locations having the same name, as long as they have different parents (the Brazilian *state* of São Paulo and the *city* of São Paulo are a good example of why this is important).

Thus, we need to have a root object in the Location trees to prevent the bug that allows duplicate information for countries to be inserted - as, without the root, countries would have a `parent_id` of `NULL`, and it is valid in MySQL to have key duplication as long as one of the fields is `NULL`.

I'm implementing this as a database migration, as this ensures that the change will be done on all ODB installations from earlier versions will be upgraded as well.

**Comment by andrechalom** [comment]
I'm also "hiding" the World location from most views, as I think having a World location exposed to the users would be more confusing than useful. This is done by a global scope [ will edit here to give a permalink ]

**Comment by andrechalom** [comment]
- The commits in this branch also fix a bug in editing Country level locations
- And finally, this branch adds a foreign key for Location parent, which should have been included since day one. This can speed up location queries significantly!

**Comment by betovicentini** [comment]
I am reopening this issue, as it seems is not yet fixed. I has able to import Bolivia twice. This is in a branch only?

**Comment by birutaibm** [comment]
@andrechalom, I think that the cause of this issue could be the some problem described at opendatabio/data#2, because the seed process occurs after the migration and deletes the world location.

**Comment by betovicentini** [comment]
Relates [](opendatabio/opendatabio-r#17)
