### ISSUE TITLE
Add "create herbarium sample" button

### ISSUE THREAD

**Issue by ricoperdiz** [opendatabio/opendatabio#192]
I can't create a new herbarium sample directly on tab "Herbarium samples", only if I create a plant, then choose to create a herbarium sample from that.
If this is the chosen path, then there is something strange because not every plant collected comes from a tagged plant, an the field "TAG" is obligatory.

Because of that, I suggest the addition of a "create herbarium sample" button after selecting tab "herbarium samples".

**Comment by andrechalom** [comment]
Hi! There are two types of herbarium samples expected in the ODB modelling. One is the herbarium sample collected from a tagged plant, and for adding that there is a button in the plant details page. 

The second type is a herbarium sample related to a location. If the sample does not come from a tagged plant, it must have an associated location. You can find the button to add a new sample in the location details screen.

**Comment by ricoperdiz** [comment]
Ok, now I get it.

Yes, this is smart, even old historical collections, sometimes without assignment of a certain locality, could be attributed at least to a country. If I have a collection like this, could I attribute it to a country, right? Without specification of a state, municipality or other specific localities?

One more thing. Should I expect a possibilty of adding herbarium samples in a batch process? I mean, an easy way to add more than one specimen at a time, just like we are able to do with DuckeWiki?

**Comment by andrechalom** [comment]
The answers are yes and yes: the ideal is to assign the sample to the most accurate location possible, so a GPS point when available, a plot / farm / gazeteer if able, or instead a city, state or even country for older historical records. And for the second question, most data is expected to be imported to ODB by batch. We're ironing out the process for locations and taxons before moving to the next data types.

**Comment by ricoperdiz** [comment]
Thanks, @andrechalom, for the answers.
