### ISSUE TITLE
display coordinate data on each herbarium sample page

### ISSUE THREAD

**Issue by ricoperdiz** [opendatabio/opendatabio#193]
I could not see geographic coordinate data on herbarium samples page. I think it would be useful to have this information at hand when seeing the specimens.

Also, there is something really important that was not clear on duckewiki, and I believe it needs some attention on opendatabio, which is making reference to where the coordinates came from, if from specimen labels, or, in the absence of this data on specimen label, if from parent locality.

**Comment by andrechalom** [comment]
Adding some things to this issue:
- Improving the lat / long display from decimal to degree/min/sec in the Locations table
- Adding a centroid lat / long display to the location show page (such as http://opendatabio.ib.usp.br/opendatabio/locations/4066)
- Adding a centroid or precise lat / long display to the plant and herbarium sample pages, both to the full list and to detail pages

The last part of the request is the hardest, as there's no way to track if the location stored comes from a specific label. What can be done is making the parent location name explicit, and this will probably be enough to differentiate the uses - with things such as "parent location: GPS point 1281 (lat long)" as opposed to "parent location: Quedas do Iguaçu (lat long)". 

The changes will be live this week, feedback is appreciated.

**Comment by ricoperdiz** [comment]
As for your last comment, I might not have been that clear in previous comment. So, let me explain it again. 
Suppose I want to download data about a certain species from opendatabio. I would like to see a column on the output file displaying the origin of the lat and long data. Were they supplied by the user, through an input of lat and long? Or were they attached to the location? 

It seems that these are the only options, right? User input, whether it is gps point already stored in database, or manually inserted, or then "system" input, when lat and long comes from the parent location, in the absence of user input. 

Is that better to understand, @andrechalom ?

**Comment by andrechalom** [comment]
In this case, I think adding a "location type" column to the report is easy. It will discriminate between "point", "municipality", etc.

**Comment by andrechalom** [comment]
The same thing about making clear the distinction between approximate location and exact location came up in a conversation with @raspereira today. I'm reopening this issue to make this more clear in the interface.

**Comment by andrechalom** [comment]
![screenshot-2018-4-18 opendatabio](https://user-images.githubusercontent.com/1994997/38948179-270d4616-4315-11e8-8c1a-44eea1290f29.png)
