### ISSUE TITLE
Add "back" button/link to sample after measurement inserted

### ISSUE THREAD

**Issue by ricoperdiz** [opendatabio/opendatabio#194]
After inserting measurement data to a certain character, we are directed to a page like this one below.

I think there should be a link to get back to the sample page (shown in the second picture).

![captura de tela 2018-02-05 as 12 19 35](https://user-images.githubusercontent.com/10851780/35826863-e63fb3be-0a6e-11e8-8212-91f3d73b72ef.png)

![captura de tela 2018-02-05 as 12 22 46](https://user-images.githubusercontent.com/10851780/35827042-8104f882-0a6f-11e8-82f5-9c2791463f62.png)

**Comment by andrechalom** [comment]
That's right! The "object" field should be a link. 

Related to #173
