### ISSUE TITLE
Proxy configuration fails

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#195]
Related by @betovicentini by e-mail

**Comment by betovicentini** [comment]
@andrechalom  the APP_URL is not being recognized by the application behind a proxy. Even specifying the right domain name in the .env file and rebooting the server or clearing the config:cache. I wonder if we need to have this extension installed for this [](https://github.com/fideloper/TrustedProxy)

**Comment by betovicentini** [comment]
solved... _ServerName_ variable in apache conf file.
