### ISSUE TITLE
DataSet / Project permissions can be incompatible

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#196]
I have access to the measurement as it is in an open dataset, but not to the measured object, as it is in a restricted project:
![screenshot-2018-2-6 opendatabio](https://user-images.githubusercontent.com/1994997/35884523-18cf2626-0b72-11e8-8659-eea12463ae56.png)

**Comment by birutaibm** [comment]
Is it really necessary to have access to measurement by the dataset? I think the usual way to access a measurement is through the measured object. But if this route to access the information is relevant, the measurements showed must apply the most restrictive access rule. So, it is necessary to select the measured object, get it's associated project and verify the user's permitions over this project.

**Comment by andrechalom** [comment]
The idea behind having the Datasets is to allow for a project managers to
have more control over the data access policies. For instance, it should be
possible to have some marked trees registered under a general project (say,
"Projeto de monitoramento da parcela permanente XYZ"), with open access.
Some measurements from historical records of this project can be associated
with open access policy. However, there may be some still unpublished data
collected from the same trees - these measurements can have a more
restricted policy. This can be accomplished by adding this measurements to
a separate dataset. This was explicitly requested by @betovicentini.

I'll try to add these conditions that you mentioned (measurement x object x
project) to the SQL in a way that won't increase too much the query
execution time...

**Comment by andrechalom** [comment]
Notice: we need to add this filter to the measurements accessed through the dataset and throught the trait definition!
