### ISSUE TITLE
Error checking mysql version during the installation

### ISSUE THREAD

**Issue by birutaibm** [opendatabio/opendatabio#198]
When I install the the opendatabio at my computer I see a message request to upgrade my mysql, that I ignore because the apt-get says that I have the last version of it.
Checking the app/Installer.php I found some strange code that is probably the cause of this issue, but I am not sure about their intent, and so I am not comfortable to change it myself.
Please, @andrechalom, can you check this file at lines 170-186 (specially, compare lines 170 and 175)?

**Comment by andrechalom** [comment]
To help the debug process, what is your output to `mysql --version`?

**Comment by birutaibm** [comment]
It is `mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper`. I am using Ubuntu 16.04, I am not sure about the answer format at other OS is the same.

**Comment by andrechalom** [comment]
Hm. You're absolutely right. Line 175 is a mistake. I've made some small changes and pushed a branch called fix198, can you see if it solves the problem?

**Comment by birutaibm** [comment]
Ok. Now, it works and I understand better the code's logic.
