### ISSUE TITLE
Location API should allow search by lat/long

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#208]
Imported from https://github.com/opendatabio/opendatabio-r/issues/17

> odb_get_locations should allow search of a locality using lat long, which could retrieve: 1) the most inclusive parent id (non-point locality); 2) and perhaps the closest point locality (informing the distance to it). This will allow to import plants and specimenes by retrieving their locationIDs from their coordinates.

This can be done combined with the adm_level, or with a flag, maybe? 

Contrast: `api/locations?lat=-14&long=-58` could return the municipality of Campo Novo do Parecis, while `api/locations?lat=-14&long=-58&adm_level=100` would return a PLOT near this lat/long. 

Alternatively, `api/locations?lat=-14&long=-58&only_adm=FALSE` would return a PLOT, TRANSECT or POINT near the lat / long.

**Comment by birutaibm** [comment]
It appears as we have 2 issues here: 1- get the location that contains the specified lat/long (that could be filtered with `adm_level` to return only country, city, point...) 2- get only `POINT` near the specified lat/long.
The first one, I think is simple to implement at ODB API, but the other is not. We need to define what means "near", get the parent level locality for the given lat/long, get all children of this locality, and filter this result based on the distance to the given lat/long. Additionally, if we define "near" in terms of meter, we need to convert this to degree coordinates. An additional problem is the case that our definition of "near" goes out of the parent locality found at the first step, this will require additional steps.

So, in my opinion, this second issue must stay out of the scope of the server API. If the server solves only the first issue this solution can be used by the clients (like opendatabio-r) to implement the second issue, if the client judge this is an important functionality.

**Comment by betovicentini** [comment]
- First type:  would be just the DetectParent function, because what one wants is the smallest polygon type location in which the point is located (WITHIN). Not the closest location.
- Second type: given a lat and long, could retrieve parent polygon first, then filter points within same parent and then calculate distance among the point and those. Perhaps a less useful API and not so urgent. 
- There is a Third Type:  Just want to check whether a given point locality is registered.
- If we add something like this to LocationController.php (index), would that be enough? Adding a querytype argument to the API.
```
if ($request->querytype) {
	        $querytype = $request->querytype;
	    } else {
		    $querytype = NULL;
	    } 
        if ($request->lat and $request->long and $querytype=='exact') {
            $geom = "POINT ($long $lat)";
	     $locations = $locations->where('geom', '=', $geom);
        }
	if ($request->lat and $request->long and ($querytype=='parent' or $querytype=='closest')) {
            $geom = "POINT ($long $lat)";
            $parent = Location::detectParent($geom, $adm_level, false);
            if ($parent) {
            	$parent_id = $parent->id;
            	$locations->whereIn('parent_id', $parent_id);
            	if ($querytype=='closest') {
		      $locations = $locations->addSelect("*",DB::Raw("ST_Distance(geom, GeomFromText('$geom')) as distance"))->where('adm_level', '>', 99);	
            	}
            }
        }
```

**Comment by andrechalom** [comment]
Added the code above, after some refactoring. It now looks like this:

https://github.com/opendatabio/opendatabio/blob/e3f20e9b3b7737533457eb614fff6c9ce18a8701/app/Http/Api/v0/LocationController.php#L45-L66

Most important changes were:
- Changed the where to whereRaw in the 'exact' query, as this is necessary to interact with a modified field such as "geom"
- Changed the adm_level to a harcoded value of 100, and changed the "whereIn" from the 'parent' query to return the actual parent, not the children of that parent.
- Refactored the 'closest' to use the withDistance scope, and added a limit (if the user does not supply a limit, 'closest' API will return the 10 nearest matches
