### ISSUE TITLE
API should be able to receive params as 0 or FALSE

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#209]
Migrated from https://github.com/opendatabio/opendatabio-r/issues/17

Currently, "adm_level=0" is not triggering the right code. @birutaibm, can you work on this issue?

**Comment by birutaibm** [comment]
There is any other API parameter that should be able receive this values or this is the case only of `adm_level`?
I just test a solution for `adm_level=0` working, but do not commit yet. I can apply it to other fields before commit it, if necessary.

**Comment by andrechalom** [comment]
What comes to my mind is the valid field for taxons. Valid=1 should return
only valid  names and valid=0 only invalid names

**Comment by birutaibm** [comment]
Taxon level too (0 = kingdom). I will commit with these 3, let me know if remember any other.
