### ISSUE TITLE
Replace "search" with "name" in API gets

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#210]
From https://github.com/opendatabio/opendatabio-r/issues/17,

> The odb_get_location search options should allow variations of the kind:
search='%colombia%'
search="colombia" only full matches
search="colombia%"

Actually, the reasoning behind this should allow the matching (ie, whether the match is exact or partial) on all character fields to be specified by the user. Thus, it makes more sense to have `name="Colombia"` or `api/locations?name="*Colombia*"`.

**Comment by birutaibm** [comment]
About remove the search: I do not remove only for compatibility purpose, but once that we are at beta versions I will remove it.

About move to base controller: I will study this possibility...

About use at Taxons: I am not sure about when to use `LIKE` operator or exact match, once that Taxons' search parameter is using an auxiliary sql function. I appreciate some help thinking about it.

About use at Persons: Actually the search parameter can be `full_name`, `abbreviation` or `email`, so I think at this case call it `search` is better than call it `name`. I can additionally/alternatively add support for these three other parameters and/or change the behavior of search to accept exact matches. Let me know what you think about this.

**Comment by andrechalom** [comment]
Yes, we need to keep compatibility from API version 1 onwards, while on API v0 we can change this.

For use at Taxons: the code must be adapted to use the "whereRaw" form, so I don't think moving it to the base Controller to reuse here is something that can easily done. Other than that, the code is the same, I believe this would work:

```php
       if ($request->name) {
            $pos = strpos($request->name, '*');
            if ($pos === FALSE)
                $taxons = $taxons->whereRaw('odb_txname(name, level, parent_id) = ?', [$request->name]);
            else {
                while ($pos !== FALSE) {
                    $request->name = substr_replace($request->name, '%', $pos, 1); 
                    $pos = strpos($request->name, '*');
                }
                $taxons = $taxons->whereRaw('odb_txname(name, level, parent_id) LIKE ?', [$request->name]);
            }   
        }
```

Notice that for "whereRaw" we pass the necessary parameters as an array (so "[$request->name]"), and they are substituted into the question marks. 

Finally, regarding People API, I believe we can have the "search" option for name, abbrev or email, and specific filters with exact match for each of them, what do you think?
