### ISSUE TITLE
World visible at web interface

### ISSUE THREAD

**Issue by birutaibm** [opendatabio/opendatabio#217]
I found `parent_id` of `Brazil` as 6840 using the API. Then, I request (by API) for this id and get no data. But if I go to the URL `http://localhost/opendatabio/locations/6840` using a browser I can see the Location World.

**Comment by andrechalom** [comment]
Hm. I guess we should remove the parent information for countries then.

**Comment by birutaibm** [comment]
The commit hides this information in the API. Maybe we add another fix to deny access to the location `Wolrd` to any user by web interface.

**Comment by andrechalom** [comment]
Working as intended. I'm submitting a fix for the web interface as well.

> odb_get_locations(list(id=c(1,2), fields=c("id", "name", "parent_id")))
  id   name parent_id
1  1 Brazil        NA
2  2   Acre         1
