### ISSUE TITLE
Whoops when accesing form/show with no logged in user

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#220]
Reported by @birutaibm

**Comment by birutaibm** [comment]
The same is happening with log in user. Let me try to describe what I think and do:

1. Logged in as admin (at ib ODB)
2. Register my user (birutaibm) as administrator of `andrechalom Data Workspace` (trying to get the same access level of @andrechalom to their forms and data)
3. Logged out as admin
4. Logged in as my user (birutaibm)
5. Go to `Others` -> `Forms`
6. Click `Formulário básico` (trying to registry measures to other plants by this form)
7. Select `Figueiras neotropicais` at `Fill form for` field and click `Fill`
8. Choose `Rafael Arantes` at `Person` field (my default user) and do not change other fields (as shown in the image)
9. Finally click Register and get the woops page with address bar of the browser showing `http://opendatabio.ib.usp.br/opendatabio/forms/1/fill`

![captura de tela de 2018-04-06 15-19-15](https://user-images.githubusercontent.com/19666564/38437675-9b32e8b8-39ae-11e8-846b-ec3b13a9628a.png)

I expect to see a page similar to the image at #159 but I don't know if this is the intended behavior.
I am reopening it for now. If this is a misunderstand of mine about the forms behavior, please, close it again and sorry.

**Comment by birutaibm** [comment]
Yes, my mistake. Now it works, sorry.
A suggestion for the code you will add is to filter the list of `Fill form for` to show only elements that has registries available to fill instead of implement an error message page. Additionally, maybe replace the `Fill Form` by a message if there is no elements to show in this list.
I like the form, good job.

**Comment by andrechalom** [comment]
The problem with displaying only projects that have plants is that in the future I want to add more filters, so it may become very difficult to implement this kind of check on all fields at once - it would become something like the filters in the lateral bar of an Amazon search (see e.g. https://www.amazon.com/s/keywords=star+trek the fields for "Book series", "Book language", etc.), and that's much more difficult to implement efficiently.
