### ISSUE TITLE
Extract query utilities

### ISSUE THREAD

**Issue by birutaibm** [opendatabio/opendatabio#221]
We have some methods that was created to help treat some complex queries. At this moment, these methods is at `App\Http\Api\v0\Controller.php` lines `35-102` of the `api` branch. When I review the `ImportPlants` and think about the `ImportVouchers` (at `App\Jobs`), I realize that the methods would be util at these classes too. So I want to extract it to another class. Maybe there is yet more places in the code that could use this new class.
What is a good name and namespace for this new class in your opinion?

**Comment by andrechalom** [comment]
Yes, you're right. None of these methods use the Controller or any other property from the current object, so they could be defined as functions outside of this class. I would recomend creating a new class `App\ODBfunctions`, with these methods as static class methods. Then, the code in the actual controllers would have to change from 

```php
 if ($request->name) {
     $this->advancedWhereIn($taxons,
             'odb_txname(name, level, parent_id)',
             $request->name,
             true);
```

to something like

```php
 if ($request->name) {
     ODBfunctions::advancedWhereIn($taxons,
             'odb_txname(name, level, parent_id)',
             $request->name,
             true);
```

I think this will make more clear where we are using the base Laravel functionality (such as `whereIn`), and where we are using our own extensions (such as `advancedWhereIn`). What do you think?

**Comment by birutaibm** [comment]
Yes, I think it is a good solution. I will apply this and continue working on api.
