### ISSUE TITLE
Data structure at API

### ISSUE THREAD

**Issue by birutaibm** [opendatabio/opendatabio#223]
Talking with @andrechalom about Measurement API, we decide to add the object type measured at the url once that this information would remain the same for all data at a given invocation of the API. But now, I review the required information for this API and note other information that will probably remains the same too. These information are "person", "date", "dataset" and bibliography (this last one is not required, but could be present). So, I want to propose a change at the actual structure of the information sent to API.

Actually the API receives a json-array where each element is a json-object representing one registry to be imported. I propose that the API receive a json-object with a member called "data" that will be the same actually received json-array, plus another member (that could absent) called "head" where the client could insert information that will be used for all registries, like the cited ones to Measurement API (including the object type measured).

I think this could be made with small changes at the API (server and client) and dramatically reduce the length of needed information at Measurement API request costing the addition of a few extra characters at other API requests.

What do you think?

**Comment by andrechalom** [comment]
That would be great. The same strategy can be used with the Plants / Sample API, in which the tagging_team, date, project can be either sent as line-by-line or in the header - I would prefer to call it "header" instead of "head". I can work on the R client to implement this changes.

**Comment by birutaibm** [comment]
I am working in this, for Plant and Sample APIs. Maybe location could use this for "datum" and "adm_level", supposing the user wants to import a lot of Point's registries without another type of data.

I am implementing in a way that header supplied information overrides data supplied ones. For example, if header contains "project=my plants" and some data registry has "project=your plants", this registry will be recorded with "project=my plants". Do you think this requirement is ok?

**Comment by andrechalom** [comment]
OK. I'll try to merge everything up to b3e772db87cd85183ad5628c7d056b9371a8b57d and work on the R client to add these new features.

**Comment by andrechalom** [comment]
I'm fixing several syntax errors present in b3e772d, please be aware of the changes when you continue the work, @birutaibm

**Comment by andrechalom** [comment]
For reference, this is what I've tried writing:

    {"header":{"level":["species"]},"data":[{"name":"Ficus guianensis"},{"name":"Ficus crocata"},{"name":"Ficus benjamina"}]}

But this fails with 

WARNING: Level for taxon Ficus guianensis not available. Skipping import of {"name":"Ficus guianensis","mobot":{"0":0,"rank":"sp.","author":"Desv. ex Ham.","valid":"No opinion","reference":"Prodr. Pl. Ind. Occid. 62, 1825","parent":"Moraceae","key":21301215,"senior":null},"ipni":{"0":2,"rank":"spec.","author":"Ham.","valid":null,"reference":"Prodr. Pl. Ind. Occid. [Hamilton] 62.","parent":"Moraceae","key":"852941-1","senior":null}}

**Comment by birutaibm** [comment]
The taxon and location support for header is not yet implemented. It looks like a good idea and I will provide this support for taxon level and location adm_level. But once that header information apply to all data you can not supply an arrays like `"level":["species"]`, you will use `"level":"species"` instead.
At a plant you can use
```
{"header":{"date":"2007-10-05","project":"Figueiras neotropicais","tagging_team":"Farache FHA,Costa PC"},
"data":[{"tag":"FD00001","location":"AM001","taxon":"Ficus citrifolia"},
{"tag":"FD00005","location":"AM005","taxon":"Ficus citrifolia"},
{"tag":"FD00010","location":"AM011","taxon":"Ficus citrifolia"},
{"tag":"FD00011","location":"AM012","taxon":"Ficus citrifolia"},
{"tag":"FD00012","location":"AM013","taxon":"Ficus citrifolia"},
{"tag":"FD00013","location":"AM014","taxon":"Ficus citrifolia"},
{"tag":"FD00014","location":"AM015","taxon":"Ficus citrifolia"}]}
```
Note that `"taxon":"Ficus citrifolia"` is used at all plants, but is not at the header because this is not supported yet. This support could be added easily if you want, my though is that when import a lot of plants it is not probable that all plants has the same specie (thinking of it at a forest).
The current supported fields at header is: date, project and tagging_team for plants; date, project and collectors for samples; and object_type, person, date, dataset and bibreference for measurements. In the case of measurements this fields is allowed only at the `header`, not at the `data`. At plants and sample it is allowed in both, but if present at the header and at the data it uses only the header provided values.

**Comment by birutaibm** [comment]
@andrechalom have you had any progress in this issue? Do you think it will be possible to adapt the R-client to this new API format or should we go back to the previous format?

**Comment by andrechalom** [comment]
Yes! Modifications to the R client are up now. Thanks!
