### ISSUE TITLE
Add link type

### ISSUE THREAD

**Issue by birutaibm** [opendatabio/opendatabio#226]
When create a new trait of `Type` `Database link`, the user is asked for the `Link type`, but this combo box gives a single option `Taxon`. The Wiki for Trait says:
`If the variable type is a link to a database object, it should specify which type of object (Taxon, Location, Voucher); it can be used to specify the host of a parasite, for example, by specifying a Plant ...`
So, we need to add support for this other types.

**Comment by andrechalom** [comment]
Are all link types ready in the api branch? I'll have to reimplement much of the resources/views/traits/elements/7.blade.php so that it can work with multiple types but also work inside forms, but I don't want to start it while you're still working on it.

**Comment by birutaibm** [comment]
It is ok to you work on it, I am not working at this time.
But it is not completely done. I remember it needs adjustment in seed (on installation process), maybe some other place that I missed.

**Comment by betovicentini** [comment]
This is fixed and Taxon, Plant, Voucher and Location are implemented in the [bigtest](/opendatabio/opendatabio/tree/bigtest) branch. Some performance issues in the autocomplete methods remain, but I will close this issue.
