### ISSUE TITLE
Decisions: Importing shapefiles

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#26]
Three possible libraries to use for importing spatial data:

- https://packagist.org/packages/muka/shape-reader
- https://packagist.org/packages/phpmyadmin/shapefile
- https://github.com/gasparesganga/php-shapefile

I'm using the last one, as it is licensed under the most permissive license and requires less dependencies.

**Comment by andrechalom** [comment]
Should we implement importing from other data formats, such as KML?

**Comment by betovicentini** [comment]
If it is not so complicated, yes, otherwise we could postpone other types, although kml are very frequently used nowadays.

**Comment by andrechalom** [comment]
It seems that KML handling is very straightforward, this should be simple to do in the R side.
