### ISSUE TITLE
Taxon data comment

### ISSUE THREAD

**Issue by betovicentini** [opendatabio/opendatabio#28]
"The only exception is the "clade" level, which is not taxonomic. It may represent subspecies, infraspecies, categories, varieties, or morphospecies (which is selected in column "category_id"), or it may represent any larger clade. The parent level checking must be done to ensure that the parent of each valid child of a clade has a strictly higher level."

Unclear why we should have a category + level fields in Taxon for clades (this shoud be only to infraspecies). It is not true that "clade" is not taxonomic, clade is just a node in the phylogeny that is not necessarily (but may be) recognized by taxonomic nomenclature as a clade lacking taxonomic ranks (ranks are clades that have an ending that indicate the hierarchy). 

However, infraspecies categories (subspecies, varieties, or morfoinfraspecies) are categories of the same level that apply only to infraspecies, not to clades. And species and morphospecies are also equivalent, so they are just published and unpublished species categories, respectively. Clades are any nodes that fit inside taxonomic ranks, but which do not have a rank. So, clade do not represent subspecies.

**Comment by andrechalom** [comment]
The correct wording would be "It may represent **a set of** subspecies, infraspecies, categories, varieties, or morphospecies". 

> Unclear why we should have a category + level fields in Taxon for clades (this shoud be only to infraspecies).

Actually, a category_level should be set only regarding "subspecies, infraspecies, categories, varieties, or morphospecies". Other clades should not have a category_level.

Does this solve this issue?

**Comment by andrechalom** [comment]
Discussion here is outdated, see new data model at https://github.com/opendatabio/opendatabio/wiki/Taxon
