### ISSUE TITLE
Where to put jQuery?

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#5]
Right now, I'm placing jQuery in the _resources/assets/js/custom.js_ file, which is then compiled by `npm`. Should we use another solution?

**Comment by betovicentini** [comment]
Link to jquery url online without placing it inside the system? minimal?

**Comment by andrechalom** [comment]
Actually, the question is about where to place custom code written in jQuery. I'm using a custom.js file, but I'm not sure that this is the expected place inside the Laravel framework. I don't think this is a big issue, just something to keep track before the code gets too large.

**Comment by andrechalom** [comment]
Using the files "custom.js" and "_custom.scss" seem to be sufficient, at least for the time being
