### ISSUE TITLE
Support for morphotypes

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#55]
The system should allow to insertion, assignment and retrieval of morphotypes.

A morphotype is a name that is not published. It may be placed at a species level (if the parent is a genus), an intraspecific category (if the parent is a species), at a genus level (if the parent is a family), or at a family level (if the parent is an order).

The last part in the name may be an abbreviation (such as "Euterpe sp.1" or "Euterpe edulis morphosp.1"), and it may be a full name (such as "Euterpe deliciosa" or "Euterpe edulis morphosp. deliciosa"). ~~If the morphotype is at genus or family level, its name must be "Indet" (for "indeterminate").~~ [EDIT: removed this, as the morphotype may be related to a genus that is being published]

A morphotype may also have a morphotype as a parent.

- [x] A published name should have the "author" registered as a string. A morphotype should have the author registered as a link to a Person. This should be made clear in the documentation.

- [ ] If a morphotype is registered at an infraspecific level, it should receive a "Morphospp" level, and not subsp, var or f. [EDIT: googling around for more uses of this, I have found none. Waiting for independent confirmation that this is actually meaningful]

**Comment by betovicentini** [comment]
#130

**Comment by andrechalom** [comment]
Yes, these are related issues. Is the above description acceptable for development?

**Comment by andrechalom** [comment]
1 - Changed the internal terminology from "morphotype" to "unpublished", as Morphotypes are used in many other different contexts (eg, https://en.wikipedia.org/wiki/Polymorphism_(biology))

2 - Implementing as currently described, due to lack of activity in this issue.
