### ISSUE TITLE
Create Plant might trigger create Location

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#70]
When the GPS position of a marked plant is known, it should be stored as a Location. The create Plant screen must have a helper to allow for the quick creation of a Location.

**Comment by betovicentini** [comment]
This applies to both plants and vouchers and is important to speed up entry and also consider some issues

If lat/long for individual plant/voucher is available, when inserting the validation should consider:
1.  Lat/Long coordinates should be unique in the Location table for point locations?
2. The parent to the new point location should be spatially selected (at least the admin levels in the location table) or any other nearby non-point location. 

Also, plants in plots/subplots may have x/y and also have individual lat/long as discussed #83
Hence when inserting plants the option to select the plot/subplot as a location and to specify lat and long in addition to x/y is important.

**Comment by andrechalom** [comment]
> This applies to both plants and vouchers and is important to speed up entry and also consider some issues

Plants, ok. For herbarium samples have some problems: we currently have two ways of creating samples. One is associated with a marked plant, in which case there is no Location for the sample itself. The second is by browsing a location and clicking "Create herbarium sample", but in this case the sample will be associated with the given location.

> If lat/long for individual plant/voucher is available, when inserting the validation should consider:
> 1.  Lat/Long coordinates should be unique in the Location table for point locations?
> 2. The parent to the new point location should be spatially selected (at least the admin levels in the location table) or any other nearby non-point location. 

For (1), lat/long are always unique in the database. 
- [ ] For (2), working on it.

> Also, plants in plots/subplots may have x/y and also have individual lat/long as discussed #83
Hence when inserting plants the option to select the plot/subplot as a location and to specify lat and long in addition to x/y is important. 
 
This is currently impossible by the current data model, and this request is in direct conflict with this excerpt from issue #83:

> No, x/y apply only to plants in plots or subplots. Plant linked to a point location (case of point quadrat) should not have x/y

So which of these is true? A plant linked to a lat/long point should have x/y or not?

I really think the entire location modeling must be thinked through and consolidated before we can progress on any of these issues.

**Comment by betovicentini** [comment]
Implemented in version 0.9.rc1. Updating Individual with lat and long coordinates instead of a location, will save the location. Either through the API or the web interface.
