### ISSUE TITLE
Tasklist for Trait / Measurement

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#77]
# Traits
- [x] Trait migration / model ( here: link type )
- [x] Trait_Category migration / model
- [x] Trait Policy (block edit once it has data)
- [x] Views / Controller methods for Trait:
- - [x] index;
- - [x] show;
- - [x] create / edit / update / store:
- - - [x]  include translatable; 
- - - [x] include object_types; 
- - - [x] link types [W23]
- - - [x] categories [W22]
- - - [x] js for conditional fields (range, link type, categories)
- [x] Translate messages
- [x] Database seeds
- [x] Provide better interface for translating TraitObject type names
# Measurements
- [ ] Data model: object -> measured
- [x] Measurement data model:  we need to have value_i for integer measurements / links
- [x] Measurement migration / model ( include Link "id" [edit: link id = value_i] )
- [x] Measurement authorize scope
- [x] Measurement Policy
- [x] Incomplete date
- [x] Scope to select only measurements that may be applicable to a class
- [x] Views / Controller methods for Measurement
- - [x] index;
- - [x] show;
- - [x] create / edit / update / store; validate object_types; 
- - - [x] categories [W22]
- - - [x] Links
- [x] validate measurement based on trait definition [W23]
- [x] include support for form elements depending on trait definition [W24]
- [x] support for multiple categorical [W22]
- [x] override morph methods for measurement for link traits [W23]
- [x] measurement lists for datasets
- [ ] list measurements on parent trait / all affected objects (plant voucher taxon location) and maybe some steps further?
- [x] Translate messages
- [x] Database seeds
- - [x] Numeric
- - [x] Text
- - [ ] Color
- - [x] Categories [W22]
- - [x] Link [W23]
- [ ] Support for color traits

+ See issue #31 on Trait ontology API

**Comment by betovicentini** [comment]
Should we have a **Date trait** type? This may be needed if measurements can be linked to datasets directly as a metadata trait type (See #76)

**Comment by andrechalom** [comment]
Color support included in b598bd6.

On "date" type traits, I'm against this for the following reasons:

- The intended use case requires that measurements must be associated directly to a Dataset. This will certainly be misused by users.
- This is not what "measurements" were originally thought to be. A Date is never a measure per se, only a metadata for something else.
- All relevant objects already have a date field. Adding other date traits will probably lead to a lot of confusion for users.

If this is really needed, please open another issue for future considerations
