### ISSUE TITLE
DataTables may fail with collation error??

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#84]
Illegal mix of collations (utf8mb4_general_ci,COERCIBLE) and (utf8mb4_unicode_ci,COERCIBLE)

**Comment by andrechalom** [comment]
This issue may (hopefuly!) be fixed in DataTables 8.0, so we'll wait for the upgrade to Laravel 5.5 (issue #75) to investigate it further

**Comment by andrechalom** [comment]
Confirmed, this bug still affects Laravel 5.5 / DataTables 8.0

**Comment by andrechalom** [comment]
Unable to reproduce under version 0.7.1

**Comment by andrechalom** [comment]
Issue reported on taxon datatables, version 0.7.2

**Comment by betovicentini** [comment]
Does not seem to be a problem anymore.
